version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.17.1
    steps:
      - checkout
      - restore_cache:
          name: Restore Pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Setup Dependencies
          command: pnpm install
      - save_cache:
          name: Save Pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.cache/pnpm
      - run:
          name: Run tests
          command: pnpm test
